### ISSUE TITLE
Large files seem to be ignored by application

### ISSUE THREAD

**Issue by lzambarda** [kohii/smoothcsv3#2]
I have some large CSV files (~800MB, millions of rows), if I try to open them with Smooth CSV 3, nothing happens. No matter whether I open them by double-clicking on the file or I drop the file onto the application's window.
I wonder if there's a timeout cancelling the loading operation, thank you!

**Comment by kohii** [comment]
Thank you for your report.

While I’m still investigating the exact cause, I have identified two potential issues:

- Parsing such large CSV files can take a significant amount of time.
- Due to browser limitations, there's a maximum height for elements. Once the total height of the table exceeds a certain value, scrolling may stop working.

I’ll try to implement a fix for what I can in the next version. Thanks again for your feedback!

**Comment by kohii** [comment]
In this release, the CSV parser's speed has been improved: https://github.com/kohii/smoothcsv3/releases/tag/v0.1.0-alpha.3
The scrolling issue will be addressed in the next release.

**Comment by lzambarda** [comment]
Hi, I've downloaded the newest version and now it does open the file I mentioned above!

Just in case it helps you with the development, I was able to scroll up to the 1.5 millionth row, then I can see that there's more elements but the scrollbar won't go any further.

The experience remains indeed smooth even with all this data 👍

**Comment by kohii** [comment]
>  I was able to scroll up to the 1.5 millionth row, then I can see that there's more elements but the scrollbar won't go any further.

I've just released a new version that should fix this issue🚀
https://github.com/kohii/smoothcsv3/releases/tag/v0.1.0-alpha.4

**Comment by lzambarda** [comment]
Awesome, arigatō!
I have opened a file with 8 million rows and the experience is very smooth - this is a game changer.
